### ISSUE TITLE
boot.task requires ClojureScript

### ISSUE THREAD

**Issue by cndreisbach** [tailrecursion/boot.task#1]
I discovered that without requiring `org.clojure/clojurescript`, using `boot.task` via `:require-tasks` results in a `java.io.FileNotFoundException`, even if only referring the non-`cljs` task. This seems sub-optimal, but maybe is intentional: I dunno!

My suggestion is to break out the `boot.task/cljs` task into a separate namespace.

**Comment by micha** [comment]
This explicit requiring of `cljs` in the `boot.task` namespace is also problematic when AOT compiling `boot.task` because the ClojureScript compiler does not work when AOT compiled. I think maybe the best thing is to require `cljs` dynamically?
